---
on:
  issues:
    types: [assigned]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: CallePuzzle/create-issue-branch@develop
        id: create_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
