name: Continuous testing
on:
  pull_request:
    branches:
      - main

env:
  GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.CT_PROJECT_ID }}
  REGION: ${{ secrets.CT_REGION }}
  SA_KEY: ${{ secrets.CT_SA_KEY }}
  SA_EMAIL: ${{ secrets.CT_SA_EMAIL }}
  TERRAFORM_VERSION: 1.1.6

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ env.SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Golang setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Download Go modules
        working-directory: test
        run: go mod download

      - name: Run Go tests
        run: go test -v
        working-directory: test
