name: Continuous testing
on:
  push:
    branches:
      - '*'
      - '!master'

env:
  GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.CT_PROJECT_ID }}
  REGION: ${{ secrets.CT_REGION }}
  SA_KEY: ${{ secrets.CT_SA_KEY }}
  SA_EMAIL: ${{ secrets.CT_SA_EMAIL }}

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '278.0.0'
          service_account_email: ${{ env.SA_EMAIL }}
          service_account_key: ${{ env.SA_KEY }}
          export_default_credentials: true

      - name: Golang setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Setup Terraform
        uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 0.12.25

      - name: Download Go modules
        working-directory: test
        run: go mod download

      - name: Run Go tests
        run: go test -v
        working-directory: test
